# Generated by Django 4.1.7 on 2023-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='firstapp/productimages'),
        ),
    ]
